@startuml
title Aplicativos de gerenciamento de músicas e artistas

class Usuario {
    - nome:  string
    - senha: string
    - pessoa: Pessoa
    + cadastrar_usuario(nome, senha, pessoa)
}

class Playlist{
    - usuario: Usuario
    - musica: Musica
    - descricao: string
}

class Musica{
    - nome: string
    - duracao: int
    - genero: string
    - artista: Artista
    - album: Album
    + cadastrar_musica(nome, duracao, genero, artista, album)
}

class Album{
    - nome: string
    + cadastrar_album(nome)
}

class Pessoa{
- nome: string
- cpf: int
- data_de_nascimento: date
- email: string
+ cadastrar_pessoa(nome, cpf, data_de_nascimento, email)
}

class Artista{
- pessoa: Pessoa
- funcao: string
+ cadastrar_artista(pessoa, funcao)
}
 
Pessoa <-- Usuario
Pessoa <-- Artista
Musica *-- Artista
Album --* Musica
Musica --* Playlist
Usuario --* Playlist
@enduml